### ISSUE TITLE
Ability to set path to graphviz directory

### ISSUE THREAD

**Issue by bartecargo** [valentiniliescu/GraphVizNet#2]
To get this to work when the current working directory of the app is not the same as the executable directory, I needed to add the following workaround:

```csharp
var renderer = new GraphViz();
Environment.CurrentDirectory = AppContext.BaseDirectory;  // workaround
return renderer.LayoutAndRenderDotGraph(dotSource, "svg");
```

Since this changes the global process state, it would be great if the directory containing the graphviz binaries could be specified, or if `AppContext.BaseDirectory` could be used directly.

**Comment by valentiniliescu** [comment]
Added `GraphVizBinariesDirectory` option to the config (see the README) and published a new version (1.0.3) of the NuGet package. Let me know if the new version works for you.

**Comment by buckthebug** [comment]
If I had looked here. 🤦‍♂️ I was struggling for 3 hours... 
It works. Thank you for the update, man! 👍

**Comment by bartecargo** [comment]
@buckthebug already confirmed it works, but this is the updated code that works for me in case it saves anyone some time:

```csharp
var renderer = new GraphViz();
renderer.Config.GraphVizBinariesDirectory = Path.Combine(AppContext.BaseDirectory, "graphviz");
return renderer.LayoutAndRenderDotGraph(dotSource, "svg");
```

Thanks, @valentiniliescu!
